services:
  managed-node:
    build:
      context: .
      dockerfile: Dockerfile_Managed_Node
    image: "cc-managed:latest"
    networks:
      - cloudcomputing
    ports:
      - "80"

  ansible-node:
    image: "willhallonline/ansible:2.16.4-alpine-3.18"
    networks:
      - cloudcomputing
    depends_on:
      - managed-node
    volumes:
      - "./ansible/hosts:/etc/ansible/hosts"
      - "./playbooks:/root/playbooks"

networks:
  cloudcomputing:
    driver: bridge
