version: "3"
services:
  tle-fetcher:
    image: qaware/tle-fetcher:1.0.0
    depends_on:
      - otel-collector
      - tempo
    ports:
      - "8080:8080"
    volumes:
      - tle_fetcher_logs:/logs
    networks:
      - default

  sky-map:
    image: qaware/sky-map:1.0.0
    environment:
      - QUARKUS_REST_CLIENT_TLE_FETCHER_URL=http://tle-fetcher:8080
    depends_on:
      - tle-fetcher
      - otel-collector
      - tempo
    ports:
      - "8088:8088"
    volumes:
      - sky_map_logs:/logs
    networks:
      - default

  otel-collector:
    image: otel/opentelemetry-collector:0.128.0
    container_name: otel-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    command: ["--config", "/etc/otel-collector-config.yaml"]
    ports:
      - "4318:4318"                   # OTLP HTTP
      - "9464:9464"                   # Prometheus metrics
    depends_on:
      - prometheus
      - loki
      - tempo

  prometheus:
    image: prom/prometheus:v3.4.1
    container_name: prometheus
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:3.4.4
    container_name: loki
    user: "0:0"  # Run as root user
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml:ro
      - loki-data:/tmp/loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  tempo:
    image: grafana/tempo:2.8.1
    container_name: tempo
    user: "0:0"  # Run as root user
    volumes:
      - ./tempo-config.yaml:/etc/tempo/tempo-local.yaml:ro
      - tempo-data:/tmp/tempo
    command: ["-config.file=/etc/tempo/tempo-local.yaml"]
    ports:
      - "3200:3200"   # HTTP query port

  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
      - ./grafana/dashboards/:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
      - tempo

volumes:
  loki-data: {}
  sky_map_logs: {}
  tempo-data: {}
  tle_fetcher_logs: {}
